### PR TITLE
added card to show who is on-call for the team

### PR DESCRIPTION
**Pull request by smitthakkar96**
Pardon my rusty frontend skills :P

### CODE REVIEW

**Comment by smitthakkar96** [comment]
@K-Phoen can you please review?

**Comment by smitthakkar96** [comment]
@K-Phoen do you have any plans to review this?

**Comment by K-Phoen** [comment]
Hey all!

Finally took the time to review this PR and play with it. I fixed a few little things, just waiting for the CI to be green and I'll merge this.

Thanks for the PR :)

**Comment by K-Phoen** [comment]
Closes https://github.com/K-Phoen/backstage-plugin-opsgenie/issues/69

**Comment by smitthakkar96** [comment]
Thank you so much @K-Phoen

**Pull request merged**
